document.write("<div id='header'>");
document.write("<a href='.'><img src='./images/newlogo2.png' id='techhoundslogo'></a>");
document.write("<a href='http://www.usfirst.org/' target='_blank'><img src='http://www.techhounds.com/images/firstlogotrans.png' alt='FIRST logo' id='firstlogo'></a>");
document.write("</div>");
document.write("<div id='myslidemenu' class='jqueryslidemenu' style='margin-top: 0px; z-index:9001; position:relative; align:center;'>");
document.write("<div style='width:100%;height:3px;background-color:#F3BD01;'></div><ul>");
document.write("<li><a href='http://www.techhounds.com'>Home</a></li>");
document.write("<li><a href='#'>Team</a>");
document.write("  <ul>");
document.write("  <li><a href='./team/aboutus/about.html'>About Us</a></li/>");
document.write("  <li><a href='./team/awards/awards.html'>Awards</a></li>");
document.write("  <li><a href='./team/branches/branches.html'>Branches</a></li>");
document.write("  <li><a href='./team/FIRSTEP/FIRSTEP.html'>FIRSTEP</a></li>");
document.write("  <li><a href='./team/pastseasonarch/seasonarchive.html'>Season Archive</a></li>");
document.write("  <li><a href='./team/members/memberbios.html'>Members</a></li>");
document.write("  </ul>");
document.write("</li>");
document.write("<li><a href='#'>FIRST</a>");
document.write("  <ul>");
document.write("  <li><a href='./FIRST/aboutFIRST/summary.html'>About FIRST</a></li>");
document.write("  <li><a href='./FIRST/gamearch/gamehistory.html'>Game Archive</a></li>");
document.write("  <li><a href='./FIRST/scholarships/scholarships.html'>Scholarships</a></li>");
document.write("  <li><a href='http://www.usfirst.org/'>FIRST Website</a></li>");
document.write("  </ul>");
document.write("</li>");
document.write("<li><a href='#'>Media</a>");
document.write("  <ul>");
document.write("  <li><a href='./media/newsletter/newsletter.html'>Newsletter</a></li>");
document.write("  <li><a href='./media/pictures/pictures.html'>Pictures</a></li>");
document.write("  <li><a href='./media/videos/videos.html'>Videos</a></li>");
document.write("  <li><a href='./media/animations/animations.html'>Animations</a></li>");
document.write("  </ul>");
document.write("</li>");
document.write("<li><a href='#'>Sponsors</a>");
document.write("  <ul>");
document.write("  <li><a href='./Sponsors/currentspons/sponsors.html'>Current Sponsors</a></li>");
document.write("  <li><a href='./Sponsors/becomespons/become_a_sponsor.html'>Become A Sponsor</a></li>");
document.write("  </ul>");
document.write("</li>");
document.write("<li><a href='#'>'11 Season</a>");
document.write("  <ul>");
document.write("  <li><a href='./FIRST/logomotion/game11.html'>2011 Information</a></li>");
document.write("  <li><a href='https://www.google.com/calendar/embed?src=6h3644bidpfp4m3da16mkjdtbk@group.calendar.google.com&ctz=America/New_York&gsessionid=OK'>Calendar</a></li>");
document.write("  </ul>");
document.write("</li>");
document.write("<li><a href='./contact/contacts.html'>Contact</a></li>");
document.write("</ul>");
document.write("<br style='clear: left' />");
document.write("</div><div style='width:100%;height:3px;background-color:#F3BD01;'>");
document.write("</div><br>");
